import type { ProductDetail, ProductSummary } from "@/types";

export interface DemoBrand {
  id: string;
  name: string;
  slug: string;
  logoUrl: string | null;
  description: string;
  country: string;
}

export interface DemoCategory {
  id: string;
  name: string;
  slug: string;
  imageUrl: string | null;
  parentId: string | null;
}

export interface DemoProduct extends ProductDetail {
  createdAt: Date;
  isFeatured: boolean;
  isBestSeller: boolean;
  isNewArrival: boolean;
}

export const DEMO_BRANDS: DemoBrand[] = [
  { id: "b_casio", name: "Casio", slug: "casio", logoUrl: "/images/brands/casio.svg", description: "Reliable timekeeping since 1946.", country: "Japan" },
  { id: "b_seiko", name: "Seiko", slug: "seiko", logoUrl: "/images/brands/seiko.svg", description: "The art of time, crafted in Japan.", country: "Japan" },
  { id: "b_citizen", name: "Citizen", slug: "citizen", logoUrl: "/images/brands/citizen.svg", description: "Better starts now.", country: "Japan" },
  { id: "b_fossil", name: "Fossil", slug: "fossil", logoUrl: "/images/brands/fossil.svg", description: "American style, genuine detail.", country: "USA" },
  { id: "b_timex", name: "Timex", slug: "timex", logoUrl: "/images/brands/timex.svg", description: "Takes a licking and keeps on ticking.", country: "USA" },
  { id: "b_hush_puppies", name: "Hush Puppies", slug: "hush-puppies", logoUrl: "/images/brands/hush-puppies.svg", description: "Classic American casual timepieces.", country: "United States" },
  { id: "b_orient", name: "Orient", slug: "orient", logoUrl: "/images/brands/orient.svg", description: "Affordable mechanical mastery.", country: "Japan" },
  { id: "b_armani", name: "Armani Exchange", slug: "armani-exchange", logoUrl: "/images/brands/armani-exchange.svg", description: "Italian-inspired fashion chronographs.", country: "Italy" },
  { id: "b_titan", name: "Titan", slug: "titan", logoUrl: "/images/brands/titan.svg", description: "Celebrating style, every second.", country: "India" },
  { id: "b_garmin", name: "Garmin", slug: "garmin", logoUrl: "/images/brands/garmin.svg", description: "GPS and fitness smartwatches.", country: "Switzerland" },
];

export const DEMO_CATEGORIES: DemoCategory[] = [
  { id: "c_men", name: "Men's Watches", slug: "mens-watches", imageUrl: "/images/categories/mens-watches.svg", parentId: null },
  { id: "c_women", name: "Women's Watches", slug: "womens-watches", imageUrl: "/images/categories/womens-watches.svg", parentId: null },
  { id: "c_luxury", name: "Luxury", slug: "luxury", imageUrl: "/images/categories/luxury.svg", parentId: null },
  { id: "c_sports", name: "Sports", slug: "sports", imageUrl: "/images/categories/sports.svg", parentId: null },
  { id: "c_smart", name: "Smart Watches", slug: "smart-watches", imageUrl: "/images/categories/smart-watches.svg", parentId: null },
  { id: "c_casual", name: "Casual", slug: "casual", imageUrl: "/images/categories/casual.svg", parentId: null },
  { id: "c_automatic", name: "Automatic", slug: "automatic", imageUrl: "/images/categories/automatic.svg", parentId: null },
  { id: "c_quartz", name: "Quartz", slug: "quartz", imageUrl: "/images/categories/quartz.svg", parentId: null },
];

// Catalogue slugs predate the real product photos in src/images/products/*.jpg.
// Map each slug to its photo; resolveProductImage() turns the .jpg path into the
// optimized static import. Unmapped products fall back to their SVG mockup.
const PRODUCT_PHOTOS: Record<string, string> = {
  "casio-vintage-a168": "casio-a168-classic-digital",
  "casio-mtp-123": "casio-f91w-classic",
  "casio-g-shock-ga2100": "casio-g-shock-ga-2100",
  "casio-mq24": "casio-classic-illuminator-ca53w",
  "casio-edifice": "casio-edifice-ecb-900",
  "seiko-5-automatic": "seiko-5-sports-automatic",
  "seiko-presage-cocktail": "seiko-presage-cocktail",
  "citizen-eco-drive": "citizen-ecco-drive-promaster",
  "citizen-ana-digi": "citizen-ecco-drive-ladies",
  "fossil-grant-chrono": "fossil-jr1437-chronograph",
  "fossil-jacqueline": "fossil-caroline-mini",
  "timex-weekender": "timex-weekender-38",
  "timex-expedition": "timex-expedition-field",
  "orient-kamasu": "orient-kamasu-diver",
  "orient-bambino-v2": "orient-bambino-v2",
  "titan-regalia": "titan-regalia-automatic",
  "titan-edge-slim": "titan-edge-ladies",
  "hush-puppies-refined": "hush-puppies-refined",
  "armani-exchange-chronograph": "armani-exchange-chronograph",
  "seiko-snk809-automatic": "seiko-snk809-automatic",
  "garmin-vivoactive-5": "garmin-vivoactive-5",
  "seiko-sports-ladies-quartz": "seiko-sports-ladies-quartz",
  "garmin-forerunner-165": "garmin-forerunner-165",

};

const img = (slug: string, n = 1) => {
  const photo = PRODUCT_PHOTOS[slug];
  // One photo per product, so every gallery angle resolves to the same image.
  if (photo) return `/images/products/${photo}.jpg`;
  const suffix = n === 1 ? "" : `-${n}`;
  return `/images/products/${slug}${suffix}.svg`;
};

function demoProduct(input: {
  id: string;
  slug: string;
  sku: string;
  name: string;
  brandId: string;
  categoryId: string;
  price: number;
  discount?: number;
  gender: "MEN" | "WOMEN" | "UNISEX";
  movement: string;
  strapMaterial: string;
  caseMaterial: string;
  caseDiameter: string;
  waterResistance: string;
  warranty?: string;
  style: string;
  colors: string[];
  rating?: number;
  ratingCount?: number;
  featured?: boolean;
  bestSeller?: boolean;
  newArrival?: boolean;
  stock?: number;
  description: string;
  specs: Record<string, string>;
}): DemoProduct {
  const brand = DEMO_BRANDS.find((b) => b.id === input.brandId)!;
  const category = DEMO_CATEGORIES.find((c) => c.id === input.categoryId)!;
  const st = input.stock ?? 12;
  return {
    id: input.id,
    slug: input.slug,
    sku: input.sku,
    name: input.name,
    price: input.price,
    discount: input.discount ?? 0,
    salePrice: input.price * (1 - (input.discount ?? 0) / 100),
    brand: { id: brand.id, name: brand.name, slug: brand.slug },
    category: { id: category.id, name: category.name, slug: category.slug },
    gender: input.gender,
    imageUrl: img(input.slug),
    ratingAvg: input.rating ?? 4.5,
    ratingCount: input.ratingCount ?? 0,
    stockStatus: st <= 0 ? "OUT_OF_STOCK" : st < 5 ? "LOW_STOCK" : "IN_STOCK",
    stock: st,
    isNewArrival: input.newArrival ?? false,
    isBestSeller: input.bestSeller ?? false,
    isFeatured: input.featured ?? false,
    description: input.description,
    strapMaterial: input.strapMaterial,
    caseMaterial: input.caseMaterial,
    caseDiameter: input.caseDiameter,
    waterResistance: input.waterResistance,
    warranty: input.warranty ?? "1 Year",
    displayType: input.movement === "Quartz" ? "Analog" : "Analog",
    occasion: input.style,
    style: input.style,
    colors: input.colors,
    specifications: input.specs,
    movement: input.movement,
    images: [
      { id: `${input.id}_img1`, url: img(input.slug, 1), alt: `${input.name} front`, sortOrder: 0 },
      { id: `${input.id}_img2`, url: img(input.slug, 2), alt: `${input.name} three-quarter`, sortOrder: 1 },
      { id: `${input.id}_img3`, url: img(input.slug, 3), alt: `${input.name} dial detail`, sortOrder: 2 },
      { id: `${input.id}_img4`, url: img(input.slug, 4), alt: `${input.name} strap`, sortOrder: 3 },
    ],
    variants: [
      {
        id: `${input.id}_v1`,
        name: input.name,
        sku: input.sku,
        color: input.colors[0],
        size: null,
        price: input.price,
        stock: st,
        stockStatus: st <= 0 ? "OUT_OF_STOCK" : st < 5 ? "LOW_STOCK" : "IN_STOCK",
        isDefault: true,
      },
    ],
    createdAt: new Date(Date.now() - Math.floor(Math.random() * 90) * 86400000),
  };
}

export const DEMO_PRODUCTS: DemoProduct[] = [
  demoProduct({
    id: "p_casio_a168",
    slug: "casio-vintage-a168",
    sku: "CAS-A168W-1",
    name: "Vintage A168",
    brandId: "b_casio",
    categoryId: "c_casual",
    price: 8999,
    discount: 10,
    gender: "UNISEX",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Resin",
    caseDiameter: "38mm",
    waterResistance: "30m",
    style: "Casual",
    colors: ["Black", "Silver"],
    rating: 4.8,
    ratingCount: 0,
    bestSeller: true,
    featured: true,
    stock: 34,
    description:
      "A timeless classic digital watch with a vintage stainless steel casing, LED backlight and our iconic retro design. A true style statement that has spanned decades.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Resin",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "38mm",
      "Water Resistance": "30m",
      Display: "Digital",
      Battery: "CR2016",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_casio_mtp",
    slug: "casio-mtp-123",
    sku: "CAS-MTP-123",
    name: "MTP-123 Analogue",
    brandId: "b_casio",
    categoryId: "c_casual",
    price: 7500,
    discount: 15,
    gender: "MEN",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "42mm",
    waterResistance: "50m",
    style: "Classic",
    colors: ["Silver", "Blue"],
    rating: 4.6,
    ratingCount: 0,
    newArrival: true,
    stock: 18,
    description:
      "A classically designed analogue watch with a clean dial and reliable quartz movement. Perfect for everyday elegance.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "42mm",
      "Water Resistance": "50m",
      Display: "Analog",
      "Calendar": "Date",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_seiko_5",
    slug: "seiko-5-automatic",
    sku: "SEI-5-8231",
    name: "Seiko 5 Automatic",
    brandId: "b_seiko",
    categoryId: "c_automatic",
    price: 42500,
    discount: 20,
    gender: "MEN",
    movement: "Automatic",
    strapMaterial: "NATO",
    caseMaterial: "Stainless Steel",
    caseDiameter: "39mm",
    waterResistance: "100m",
    style: "Classic",
    colors: ["Blue", "Green"],
    rating: 4.9,
    ratingCount: 0,
    bestSeller: true,
    featured: true,
    stock: 12,
    description:
      "The watch that changed the world of mechanical watches. In-house automatic movement, day-date display and a visible case back.",
    specs: {
      Movement: "Automatic (Calibre 7S26)",
      "Case Material": "Stainless Steel",
      "Strap Material": "NATO",
      "Case Diameter": "39mm",
      "Water Resistance": "100m",
      Display: "Analog",
      "Power Reserve": "41 hours",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_citizen_eco",
    slug: "citizen-eco-drive",
    sku: "CTZ-ECD-2210",
    name: "Eco-Drive AW1254",
    brandId: "b_citizen",
    categoryId: "c_quartz",
    price: 38500,
    discount: 12,
    gender: "MEN",
    movement: "Eco-Drive",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "41mm",
    waterResistance: "100m",
    style: "Classic",
    colors: ["Silver", "Black"],
    rating: 4.7,
    ratingCount: 0,
    featured: true,
    stock: 15,
    description:
      "Powered by light, never needs a battery. Citizen's legendary Eco-Drive technology in an elegant everyday silhouette.",
    specs: {
      Movement: "Eco-Drive",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "41mm",
      "Water Resistance": "100m",
      Display: "Analog",
      Power: "Light-powered",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_fossil_grant",
    slug: "fossil-grant-chrono",
    sku: "FOS-GRT-3771",
    name: "Grant Chronograph",
    brandId: "b_fossil",
    categoryId: "c_casual",
    price: 28500,
    discount: 25,
    gender: "MEN",
    movement: "Quartz",
    strapMaterial: "Leather",
    caseMaterial: "Stainless Steel",
    caseDiameter: "44mm",
    waterResistance: "50m",
    style: "Classic",
    colors: ["Brown", "Black"],
    rating: 4.5,
    ratingCount: 0,
    bestSeller: true,
    stock: 9,
    description:
      "A vintage-inspired chronograph with a flexible stainless steel case, exhibition back and genuine leather strap.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Leather",
      "Case Diameter": "44mm",
      "Water Resistance": "50m",
      Display: "Chronograph",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_timex_weekender",
    slug: "timex-weekender",
    sku: "TMX-WKND-22",
    name: "Weekender 38mm",
    brandId: "b_timex",
    categoryId: "c_casual",
    price: 11999,
    discount: 18,
    gender: "UNISEX",
    movement: "Quartz",
    strapMaterial: "Nylon",
    caseMaterial: "Resin",
    caseDiameter: "38mm",
    waterResistance: "30m",
    style: "Minimal",
    colors: ["Navy", "Black", "Olive"],
    rating: 4.4,
    ratingCount: 0,
    newArrival: true,
    stock: 40,
    description:
      "The iconic Weekend with an Indiglo night-light. Colourful, casual and endlessly versatile.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Resin",
      "Strap Material": "Nylon",
      "Case Diameter": "38mm",
      "Water Resistance": "30m",
      Display: "Analog",
      "Feature": "Indiglo",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_hush_puppies_refined",
    slug: "hush-puppies-refined",
    sku: "HSP-REF-3412",
    name: "Refined Dress Watch",
    brandId: "b_hush_puppies",
    categoryId: "c_casual",
    price: 18500,
    discount: 15,
    gender: "MEN",
    movement: "Quartz",
    strapMaterial: "Leather",
    caseMaterial: "Stainless Steel",
    caseDiameter: "41mm",
    waterResistance: "30m",
    style: "Classic",
    colors: ["Brown", "Gold"],
    rating: 4.5,
    ratingCount: 0,
    featured: true,    stock: 18,
    description:
      "Clean lines and a slim profile make this an effortless everyday dress watch, equally at home in the office or at dinner.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Genuine Leather",
      "Case Diameter": "41mm",
      "Water Resistance": "30m",
      Display: "Analog",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_orient_kamasu",
    slug: "orient-kamasu",
    sku: "ORT-KAM-AA3",
    name: "Kamasu Automatic",
    brandId: "b_orient",
    categoryId: "c_automatic",
    price: 52000,
    discount: 15,
    gender: "MEN",
    movement: "Automatic",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "41mm",
    waterResistance: "200m",
    style: "Sport",
    colors: ["Green", "Red", "Black"],
    rating: 4.8,
    ratingCount: 0,
    bestSeller: true,
    stock: 11,
    description:
      "A dive-ready automatic with sapphire crystal, screw-down crown and 200m water resistance. Outstanding value in mechanical watchmaking.",
    specs: {
      Movement: "Automatic Calibre F6922",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "41mm",
      "Water Resistance": "200m",
      "Crystal": "Sapphire",
      "Power Reserve": "40 hours",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_armani_exchange_chrono",
    slug: "armani-exchange-chronograph",
    sku: "AEX-CHR-4120",
    name: "Exchange Chronograph",
    brandId: "b_armani",
    categoryId: "c_luxury",
    price: 42500,
    discount: 18,
    gender: "MEN",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "45mm",
    waterResistance: "100m",
    style: "Classic",
    colors: ["Silver", "Blue"],
    rating: 4.6,
    ratingCount: 0,
    bestSeller: true,    stock: 12,
    description:
      "A sharp steel chronograph with a sunray blue dial and clean sub-dials — a confident everyday statement piece.",
    specs: {
      Movement: "Quartz Chronograph",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "45mm",
      "Water Resistance": "100m",
      Display: "Chronograph",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_casio_gshock",
    slug: "casio-g-shock-ga2100",
    sku: "CAS-GA2100-1A",
    name: "G-Shock GA-2100",
    brandId: "b_casio",
    categoryId: "c_sports",
    price: 18999,
    discount: 8,
    gender: "UNISEX",
    movement: "Quartz",
    strapMaterial: "Resin",
    caseMaterial: "Resin",
    caseDiameter: "45mm",
    waterResistance: "200m",
    style: "Sport",
    colors: ["Black", "Red", "Green"],
    rating: 4.7,
    ratingCount: 0,
    bestSeller: true,
    stock: 28,
    description:
      "The octagonal icon. Shock-resistant, water-resistant to 200m and engineered to be the toughest watch in its class.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Carbon Resin",
      "Strap Material": "Resin",
      "Case Diameter": "45mm",
      "Water Resistance": "200m",
      Display: "Analog-Digital",
      "Shock": "Shock Resistant",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_titan_regalia",
    slug: "titan-regalia",
    sku: "TIT-REG-58",
    name: "Regalia Dress Watch",
    brandId: "b_titan",
    categoryId: "c_women",
    price: 21500,
    discount: 20,
    gender: "WOMEN",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "28mm",
    waterResistance: "30m",
    style: "Classic",
    colors: ["Rose Gold", "Silver"],
    rating: 4.5,
    ratingCount: 0,
    featured: true,
    stock: 16,
    description:
      "A refined dress watch with a mother-of-pearl dial and rose-gold finishing. Elegance distilled to its purest form.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "28mm",
      "Water Resistance": "30m",
      Dial: "Mother of Pearl",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_fossil_jacqueline",
    slug: "fossil-jacqueline",
    sku: "FOS-JQ-955",
    name: "Jacqueline Quartz",
    brandId: "b_fossil",
    categoryId: "c_women",
    price: 23000,
    discount: 14,
    gender: "WOMEN",
    movement: "Quartz",
    strapMaterial: "Leather",
    caseMaterial: "Stainless Steel",
    caseDiameter: "32mm",
    waterResistance: "30m",
    style: "Classic",
    colors: ["Blush", "Black"],
    rating: 4.6,
    ratingCount: 0,
    newArrival: true,
    stock: 22,
    description:
      "Clean lines and a delicate profile define the Jacqueline. An everyday watch that goes from desk to dinner.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Leather",
      "Case Diameter": "32mm",
      "Water Resistance": "30m",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_seiko_snk809",
    slug: "seiko-snk809-automatic",
    sku: "SKX-SNK-809",
    name: "5 SNK809 Automatic",
    brandId: "b_seiko",
    categoryId: "c_automatic",
    price: 31500,
    discount: 12,
    gender: "MEN",
    movement: "Automatic",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "39mm",
    waterResistance: "100m",
    style: "Sport",
    colors: ["Black", "White"],
    rating: 4.7,
    ratingCount: 0,
    bestSeller: true,    stock: 16,
    description:
      "A cult-favourite automatic with a crisp white dial and date at 3 o’clock, running on Seiko’s 4R self-winding movement.",
    specs: {
      Movement: "Automatic 4R",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "39mm",
      "Water Resistance": "100m",
      Display: "Analog",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_garmin_vivoactive5",
    slug: "garmin-vivoactive-5",
    sku: "GRM-VA5-001",
    name: "Vivoactive 5",
    brandId: "b_garmin",
    categoryId: "c_smart",
    price: 28500,
    discount: 10,
    gender: "UNISEX",
    movement: "Smart",
    strapMaterial: "Silicone",
    caseMaterial: "Polymer",
    caseDiameter: "45mm",
    waterResistance: "50m",
    style: "Sport",
    colors: ["Black", "Blue", "Pink"],
    rating: 4.6,
    ratingCount: 0,
    newArrival: true,    stock: 42,
    description:
      "An AMOLED fitness watch with built-in GPS, stress tracking and sleep coaching, with a battery that lasts up to 11 days.",
    specs: {
      Movement: "Smart",
      "Case Material": "Fiber-reinforced Polymer",
      "Strap Material": "Silicone",
      "Case Diameter": "45mm",
      "Water Resistance": "50m",
      Display: "AMOLED",
      Battery: "Up to 11 Days",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_casio_mq24",
    slug: "casio-mq24",
    sku: "CAS-MQ24-7B",
    name: "Classic Women's MQ24",
    brandId: "b_casio",
    categoryId: "c_women",
    price: 4999,
    discount: 10,
    gender: "WOMEN",
    movement: "Quartz",
    strapMaterial: "Resin",
    caseMaterial: "Resin",
    caseDiameter: "32mm",
    waterResistance: "30m",
    style: "Minimal",
    colors: ["White", "Pink"],
    rating: 4.5,
    ratingCount: 0,
    featured: true,
    stock: 60,
    description:
      "The beloved MQ24 in a petite 32mm case. Simple, affordable and effortlessly charming.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Resin",
      "Strap Material": "Resin",
      "Case Diameter": "32mm",
      "Water Resistance": "30m",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_seiko_presage",
    slug: "seiko-presage-cocktail",
    sku: "SEI-PSG-6421",
    name: "Presage Cocktail Time",
    brandId: "b_seiko",
    categoryId: "c_luxury",
    price: 120000,
    discount: 5,
    gender: "MEN",
    movement: "Automatic",
    strapMaterial: "Leather",
    caseMaterial: "Stainless Steel",
    caseDiameter: "40mm",
    waterResistance: "50m",
    style: "Classic",
    colors: ["Blue", "Green"],
    rating: 4.9,
    ratingCount: 0,
    featured: true,
    stock: 5,
    description:
      "Inspired by cocktails, finished like fine jewellery. The dial of the Presage captures the shimmer of a perfectly poured Old Fashioned.",
    specs: {
      Movement: "Automatic 4R35",
      "Case Material": "Stainless Steel",
      "Strap Material": "Leather",
      "Case Diameter": "40mm",
      "Water Resistance": "50m",
      "Crystal": "Box Sapphire",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_casio_edifice",
    slug: "casio-edifice",
    sku: "CAS-EDF-1200",
    name: "Edifice EFS-S570",
    brandId: "b_casio",
    categoryId: "c_sports",
    price: 21000,
    discount: 16,
    gender: "MEN",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "48mm",
    waterResistance: "100m",
    style: "Sport",
    colors: ["Blue", "Black"],
    rating: 4.6,
    ratingCount: 0,
    bestSeller: true,
    stock: 19,
    description:
      "Racing-inspired chronograph inspired by motorsport. Sapphire-coated glass and bold legibility.",
    specs: {
      Movement: "Quartz Chronograph",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "48mm",
      "Water Resistance": "100m",
      "Crystal": "Sapphire",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_orient_bambino",
    slug: "orient-bambino-v2",
    sku: "ORT-BAM-V2",
    name: "Bambino Version 2",
    brandId: "b_orient",
    categoryId: "c_automatic",
    price: 48000,
    discount: 18,
    gender: "MEN",
    movement: "Automatic",
    strapMaterial: "Leather",
    caseMaterial: "Stainless Steel",
    caseDiameter: "40mm",
    waterResistance: "30m",
    style: "Classic",
    colors: ["Gold", "Silver"],
    rating: 4.7,
    ratingCount: 0,
    featured: true,
    stock: 7,
    description:
      "The legendary dress watch. A hand-winding automatic with a rich domed dial that looks twice its price.",
    specs: {
      Movement: "Automatic Calibre F6724",
      "Case Material": "Stainless Steel",
      "Strap Material": "Leather",
      "Case Diameter": "40mm",
      "Water Resistance": "30m",
      "Power Reserve": "40 hours",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_seiko_ladies_quartz",
    slug: "seiko-sports-ladies-quartz",
    sku: "SKQ-SPT-L81",
    name: "Sports Ladies Quartz",
    brandId: "b_seiko",
    categoryId: "c_women",
    price: 16500,
    discount: 20,
    gender: "WOMEN",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "32mm",
    waterResistance: "50m",
    style: "Casual",
    colors: ["Gold", "White"],
    rating: 4.4,
    ratingCount: 0,
    stock: 26,
    description:
      "A slim everyday quartz watch for her: a clean dial, a light bracelet and 50m water resistance that handles daily splashes.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "32mm",
      "Water Resistance": "50m",
      Display: "Analog",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_garmin_forerunner165",
    slug: "garmin-forerunner-165",
    sku: "FRM-165-001",
    name: "Forerunner 165",
    brandId: "b_garmin",
    categoryId: "c_sports",
    price: 34500,
    discount: 15,
    gender: "UNISEX",
    movement: "Smart",
    strapMaterial: "Silicone",
    caseMaterial: "Polymer",
    caseDiameter: "43mm",
    waterResistance: "50m",
    style: "Sport",
    colors: ["Black", "White"],
    rating: 4.7,
    ratingCount: 0,
    newArrival: true,    stock: 22,
    description:
      "A lightweight GPS running watch with an AMOLED display, race insights and up to 13 days of battery life.",
    specs: {
      Movement: "Smart",
      "Case Material": "Fiber-reinforced Polymer",
      "Strap Material": "Silicone",
      "Case Diameter": "43mm",
      "Water Resistance": "50m",
      Display: "AMOLED",
      Battery: "Up to 13 Days",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_timex_expedition",
    slug: "timex-expedition",
    sku: "TMX-EXP-43",
    name: "Expedition Field",
    brandId: "b_timex",
    categoryId: "c_sports",
    price: 10999,
    discount: 20,
    gender: "MEN",
    movement: "Quartz",
    strapMaterial: "Fabric",
    caseMaterial: "Aluminium",
    caseDiameter: "43mm",
    waterResistance: "50m",
    style: "Sport",
    colors: ["Green", "Black"],
    rating: 4.5,
    ratingCount: 0,
    newArrival: true,
    stock: 25,
    description:
      "Built for the outdoors with a rugged field-inspired dial and an Indiglo night light.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Aluminium",
      "Strap Material": "Fabric",
      "Case Diameter": "43mm",
      "Water Resistance": "50m",
      "Feature": "Indiglo",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_titan_edge",
    slug: "titan-edge-slim",
    sku: "TIT-EDG-12",
    name: "Edge Slim 6.14mm",
    brandId: "b_titan",
    categoryId: "c_casual",
    price: 32000,
    discount: 15,
    gender: "MEN",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "41mm",
    waterResistance: "30m",
    style: "Minimal",
    colors: ["Silver", "Rose Gold"],
    rating: 4.6,
    ratingCount: 0,
    stock: 13,
    description:
      "A record-settingly slim case at just 6.14mm. Designed in India, worn across the world.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "41mm",
      "Thickness": "6.14mm",
      "Water Resistance": "30m",
      Warranty: "1 Year",
    },
  }),
  demoProduct({
    id: "p_citizen_ana",
    slug: "citizen-ana-digi",
    sku: "CTZ-AND-5900",
    name: "Ana-Digi Temp",
    brandId: "b_citizen",
    categoryId: "c_casual",
    price: 15000,
    discount: 10,
    gender: "UNISEX",
    movement: "Quartz",
    strapMaterial: "Stainless Steel",
    caseMaterial: "Stainless Steel",
    caseDiameter: "44mm",
    waterResistance: "100m",
    style: "Sport",
    colors: ["Blue", "Black"],
    rating: 4.3,
    ratingCount: 0,
    stock: 21,
    description:
      "A rugged analog-digital combination watch with thermometer and chronograph. Retro cool, built to last.",
    specs: {
      Movement: "Quartz",
      "Case Material": "Stainless Steel",
      "Strap Material": "Stainless Steel",
      "Case Diameter": "44mm",
      "Water Resistance": "100m",
      Display: "Analog-Digital",
      Warranty: "1 Year",
    },
  }),
];

// Demo/practice build: sample reviews for layout only — not real customers.
export const DEMO_REVIEWS = [
  {
    id: "r1",
    author: "Ahmed R.",
    rating: 5,
    content:
      "The watch looked even better than the pictures. Delivery was fast and packaging was premium. Highly recommended!",
    date: new Date("2026-08-12"),
    verified: false,
    productId: "p_casio_a168",
  },
  {
    id: "r2",
    author: "Fatima S.",
    rating: 5,
    content:
      "Gorgeous piece. Feels much more expensive than it is. The dial is stunning in natural light.",
    date: new Date("2026-07-28"),
    verified: false,
    productId: "p_seiko_presage",
  },
  {
    id: "r3",
    author: "Bilal K.",
    rating: 4,
    content:
      "Solid build quality and accurate timekeeping. Strap is a bit stiff initially but softens with wear.",
    date: new Date("2026-08-03"),
    verified: false,
    productId: "p_casio_gshock",
  },
  {
    id: "r4",
    author: "Mariam T.",
    rating: 5,
    content:
      "Bought this for my wife's birthday. She hasn't taken it off since! Beautiful rose-gold finish.",
    date: new Date("2026-06-19"),
    verified: false,
    productId: "p_titan_regalia",
  },
  {
    id: "r5",
    author: "Umar A.",
    rating: 4,
    content:
      "Excellent automatic watch for the price. The exhibition case back is a nice touch. Shipping took 3 days.",
    date: new Date("2026-05-30"),
    verified: false,
    productId: "p_orient_kamasu",
  },
];

// Demo/practice build: sample reviews for layout only — not real customers.
export const DEMO_TESTIMONIALS = [
  {
    quote:
      "Coming from a big watch store, the experience here was honestly smoother. Great products, real quality.",
    author: "Ahmed R.",
    role: "Sample review",
    rating: 5,
  },
  {
    quote:
      "I found exactly the watch I wanted using the Watch Finder. It felt like they read my mind.",
    author: "Hira M.",
    role: "Sample review",
    rating: 5,
  },
  {
    quote: "A timeless classic, delivered in two days. This is how online shopping should feel.",
    author: "Zain B.",
    role: "Sample review",
    rating: 5,
  },
];